services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    NewsletterDefinitionBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('NewsletterDefinitionBundle')"